### ISSUE TITLE
systemd timer fails to start

### ISSUE THREAD

**Issue by thisischrys** [troyengel/petrified#3]
I've setup using /etc/petrified.conf, and sudo petrified works flawlessly
however systemctl start petrified.timer fails
all that's visible in the systemd log is 

    systemd[1]: Failed to start Daily petrified update.
    -- Subject: Unit petrified.timer has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    --
    -- Unit petrified.timer has failed
    --
    -- The result is failed

I've tried enabling logging to journal, logfile (and uncommented PET_LOG) and stdout but that doesn't seem to add any more info to anything.

**Comment by troyengel** [comment]
Holy cow, someone is using the systemd units! :) So the way "instanced" units work is outlined here:

http://0pointer.de/blog/projects/instances.html

The short version - you use the provided petrified@.service file (which lives in the main /lib/system/systemd/ area) and have a symlink with the network interface name in the symlink to "use" it; the timer file itself is not what you actually start. Example on my laptop here:

````
$ ip link show | grep ^[0-9] | awk '{print $2}'
lo:
enp0s25:
wlp3s0:
````

The last one is my wifi using petrified - I would create a symlink like this:
````
ln -s /lib/systemd/system/petrified@.service /etc/systemd/system/petrified@wlp3s0.service
````
... then use the standard systemctl commands on that symlink name. I don't actually use the systemd units myself, instead preferring to run it as my user with configs in my home directory and with user cron (technically fcron) jobs. The systemd units were requested by another user, they're not well tested by me but should work fine once set up correctly. Give it a shot, report back later...

**Comment by thisischrys** [comment]
Arch user, and since they optionally come with the package and ddclient was being a pain (and I don't have cron installed on that machine, it's a pretty minimal VM server)

Thanks for the link, now I finally understand those netctl and dhcpcd services.

Unfortunately I'm still running into problems

    petrified@eno16780032.service - Run petrified as eno16780032
    Loaded: loaded (/usr/lib/systemd/system/petrified@.service; enabled; vendor preset: disabled)
    Active: failed (Result: exit-code) since Fri 2016-01-22 02:46:43 CET; 5min ago
    Process: 2941 ExecStart=/usr/bin/petrified (code=exited, status=217/USER)
    Main PID: 2941 (code=exited, status=217/USER)

    Jan 22 02:46:43 alfheim systemd[1]: Starting Run petrified as eno16780032...
    Jan 22 02:46:43 alfheim systemd[1]: petrified@eno16780032.service: Main process exited, code=exited, status=217/USER
    Jan 22 02:46:43 alfheim systemd[1]: Failed to start Run petrified as eno16780032.
    Jan 22 02:46:43 alfheim systemd[1]: petrified@eno16780032.service: Unit entered failed state.
    Jan 22 02:46:43 alfheim systemd[1]: petrified@eno16780032.service: Failed with result 'exit-code'.

**Comment by troyengel** [comment]
Gotcha -- I don't have time right this second, but I'll try and get a chance to dig into it here maybe tomorrow or this weekend. I really didn't think anyone would actually use those, guess I have to go make sure they actually *work*, huh? :)

**Comment by thisischrys** [comment]
Appreciate it. And take your time, it's just a silly little hobby project :p

If you need anything from me, let me know/

**Comment by troyengel** [comment]
Heya Chris, can you triy this simple thing? Edit this file:

/usr/lib/systemd/system/petrified@.service

...and just comment out the line that begins with "User=%i" -- I think back when I was making these I got confused as to what the idea was, the %i is the name of the interface, not the name of the User that should run it. Or maybe what I was trying to do was something more like this:

    /etc/systemd/system/petrified@thisischyrs.service

...so as to allow running it as any *user* not an interface. Commenting that out seems to do what's expected in a  5 second test:

```
# systemctl start petrified@wlp3s0.service
Job for petrified@wlp3s0.service failed because the control process exited with error code. See "systemctl status petrified@wlp3s0.service" and "journalctl -xe" for details.

-- Unit petrified@wlp3s0.service has begun starting up.
Jan 23 08:45:28 grimm petrified[22867]: DDNS_KEY must be configured, exiting.
Jan 23 08:45:28 grimm systemd[1]: petrified@wlp3s0.service: Main process exited,
```

...which is expected for me (as I use ~/.petrifiedrc on this laptop). Thinking forward, the better design is that the %i could be used to instead run a command like this:

````
/usr/bin/petrified -c /etc/petrified-%i.conf
````
... or something? The idea being that maybe what the systemd unit should do is allow for running multiple interfaces, each one needing a custom config that attaches to that interface. I'm open to design here, I think I was trying to use a "don't run this as root!" concept, but it actually makes more sense to run it on an interface, not a user?

Then maybe the extra answer to that problem is the package petrified would create a user named 'petrified' or something, but then we have to fight over ownership of /var/cache/petrified (as I don't want to make a user if you're *not* using the petrified-systemd package). I guess the real question is, is there any harm or downside to just letting it run as root - not really the *best* security, but hard to ship a systemd unit file with a predefined user otherwise.

Or, I guess we could always use 'nobody' or 'daemon' system users instead, those are pretty darn standard on any distribution. Hmmm.....

**Comment by troyengel** [comment]
Followup to myself - or maybe the right design is to take advantage of the new User level systemd *in conjunction* with the system level; meaning we ship what's there as-is (which means it runs as root and reads /etc/petrified.conf - simple use case) and then we *also* provide the same unit for Users as outlined in the Arch wiki:

https://wiki.archlinux.org/index.php/Systemd/User

I'm looking on my laptop here and have a /usr/lib/systemd/user/vncserver@.service as a template:

````
#
# /usr/lib/systemd/user/vncserver@.service
#
# 1. Switches for vncserver should be entered in ~/.vnc/config rather than
#    hard-coded into this unit file. See the vncserver(1) manpage.
#
# 2. Users wishing for the server to continue running after the owner logs
#    out MUST enable 'linger' with loginctl like this:
#    `loginctl enable-linger username`
#    
# 3. The server can be enabled and started like this once configured:
#    `systemctl --user start vncserver@:<display>.service`
#    `systemctl --user enable vncserver@:<display>.service`

[Unit]
Description=Remote desktop service (VNC)
After=syslog.target network.target

[Service]
Type=forking
ExecStartPre=/bin/sh -c '/usr/bin/vncserver -kill %i > /dev/null 2>&1 || :'
ExecStart=/usr/bin/vncserver %i
ExecStop=/usr/bin/vncserver -kill %i

[Install]
WantedBy=default.target
````

That way if you *want* to run it as another user you could instantiate that in your personal systemd startup. I think that's a cleaner way to keep it simple for both use cases - let the end user choose the method they want and don't force one method or the other on them. Whatchya think?

**Comment by thisischrys** [comment]
I thought it was weird it said "running as <network interface"
it works fine with that commented out
and yeah, adding a user service files seems to be the way to go

**Comment by thisischrys** [comment]
caveat: it starts fine, but enabling it results in "Too many levels of symbolic links"
but if I understand your proposed solution, this wouldn't be a problem anymore, so I'll just leave it for now

**Comment by troyengel** [comment]
That makes sense -- creating the link manually in /etc/ is enabling it; it's the manual way instead of using "systemctl enable foo" (so you can erase the symlink created, then run "systemctl enable foo@interface.service" and it'll do the same thing).

I'm reading up on systemd.timers, and it's actually that you're supposed to enable the timer, but run the service. And given that, the provided .timer is wrong -- it needs to have an override to the "Unit=" to include the %i in the name, so it's getting complicated for the actual setup portions to do it both as a system level and user level event.

I'm starting to think trying to use instanced units is just a death spiral for this use case, and maybe the better way is to use the "override" method if you want to have N+1 running at once and specify multiple config files. (you create something like /etc/systemd/system/petrified.service.d/wlp3s0.conf that has an Exec= line over ride using the -c <conf> param).

**Comment by troyengel** [comment]
That, and I just learned using Type=oneshot actually causes the Timer to get disabled after the first run, we need to use Type=simple in order for the timer to repeatedly run the script. So what's in the current code it's just super broken, sorry about that. :-/

**Comment by troyengel** [comment]
I think I have it sorted - can you test the latest for me? First make a backup of your /etc/petrified.conf (just in case, there were no changes) then undo any of the symlinks we did in your /etc/systemd/system/ directory here. Reset to default if you will.

Download the PKGBUILD-git and petrified.archinst from here into an empty dir:

* https://github.com/troyengel/petrified/tree/master/arch

...then a standard "makepkg -p PKGBUILD-git" and a "sudo pacman -U *.xz" to upgrade (it will prompt you about removing the standard packages, I have conflicts() configured for Arch in the PKGBUILDs). After that, you should be able to do this as root:

````
systemctl start petrified.timer && systemctl enable petrified.timer
systemctl list-timers petrified.timer
````

I tested this as root (system level) and also the new per user the same way:

````
$ systemctl --user start petrified.timer && systemctl --user enable petrified.timer 
Created symlink from /home/tengel/.config/systemd/user/multi-user.target.wants/petrified.timer to /usr/lib/systemd/user/petrified.timer.

$ systemctl --user list-timers petrified.timer
NEXT                         LEFT          LAST                         PASSED  
Sat 2016-01-23 18:00:00 CST  5h 25min left Sat 2016-01-23 12:33:54 CST  16s ago 

1 timers listed.
Pass --all to see loaded but inactive timers, too.
````

In testing I lowered the OnCalendar to 5 minutes in the timer to ensure it fired off repeatedly as intended (fixing the unit type=simple). If this works out for you also I think we're golden -- I'll just write some systemd doc entries in the man page / README.pod file and tag a new release. Side note: I also changed the timer from daily to every 6 hours, figured why not - I bet some people's dynamic IPs change while they sleep or something, it's completely random.

**Comment by troyengel** [comment]
Version 1.0.6 is tagged & released, Arch package updated.
